plots_flag: false
force_center:
  mode: true
  x: 540
  y: 531

search_radius: 18

pf8:
  max_num_peaks: 10000
  adc_threshold: 0
  minimum_snr: 5
  min_pixel_count: 5
  max_pixel_count: 1000
  local_bg_radius: 10
  min_res: 20
  max_res: 200

starting_frame: 200

offset:
  x: 0
  y: 0

peak_region:
  min: 0
  max: 0

outlier_distance: 20

canny:
  sigma: 0
  low_threshold: 0
  high_threshold: 0

method: center_of_mass

bragg_pos_center_of_mass: -1

pixels_per_peak: 8

skip_method:
  - minimize_peak_fwhm
  - circle_detection

skip_pol: true
